import requests


def clamp(x: float, a: float, b: float):
    return max(a, min(x, b))


url = "https://ddragon.leagueoflegends.com/api/versions.json"
data = requests.get(url).json()
latestVersion = data[0]

url = f"https://ddragon.leagueoflegends.com/cdn/{latestVersion}/data/en_US/champion.json"
data = requests.get(url).json()["data"]

riotChampionsNames = {-1: "Null"}
for champ_data in data.items():
    riotChampionsNames[int(champ_data[1]["key"])] = champ_data[1]["name"]


championsIndices = {
    "Null"                 : 0,
    "Aatrox"               : 1,
    "Ahri"                 : 2,
    "Akali"                : 3,
    "Akshan"               : 4,
    "Alistar"              : 5,
    "Ambessa"              : 6,
    "Amumu"                : 7,
    "Anivia"               : 8,
    "Annie"                : 9,
    "Aphelios"             : 10,
    "Ashe"                 : 11,
    "Aurelion Sol"         : 12,
    "Aurora"               : 13,
    "Azir"                 : 14,
    "Bard"                 : 15,
    "Bel'Veth"             : 16,
    "Blitzcrank"           : 17,
    "Brand"                : 18,
    "Braum"                : 19,
    "Briar"                : 20,
    "Caitlyn"              : 21,
    "Camille"              : 22,
    "Cassiopeia"           : 23,
    "Cho'Gath"             : 24,
    "Corki"                : 25,
    "Darius"               : 26,
    "Diana"                : 27,
    "Dr. Mundo"            : 28,
    "Draven"               : 29,
    "Ekko"                 : 30,
    "Elise"                : 31,
    "Evelynn"              : 32,
    "Ezreal"               : 33,
    "Fiddlesticks"         : 34,
    "Fiora"                : 35,
    "Fizz"                 : 36,
    "Galio"                : 37,
    "Gangplank"            : 38,
    "Garen"                : 39,
    "Gnar"                 : 40,
    "Gragas"               : 41,
    "Graves"               : 42,
    "Gwen"                 : 43,
    "Hecarim"              : 44,
    "Heimerdinger"         : 45,
    "Hwei"                 : 46,
    "Illaoi"               : 47,
    "Irelia"               : 48,
    "Ivern"                : 49,
    "Janna"                : 50,
    "Jarvan IV"            : 51,
    "Jax"                  : 52,
    "Jayce"                : 53,
    "Jhin"                 : 54,
    "Jinx"                 : 55,
    "Kai'Sa"               : 56,
    "Kalista"              : 57,
    "Karma"                : 58,
    "Karthus"              : 59,
    "Kassadin"             : 60,
    "Katarina"             : 61,
    "Kayle"                : 62,
    "Kayn"                 : 63,
    "Kennen"               : 64,
    "Kha'Zix"              : 65,
    "Kindred"              : 66,
    "Kled"                 : 67,
    "Kog'Maw"              : 68,
    "K'Sante"              : 69,
    "LeBlanc"              : 70,
    "Lee Sin"              : 71,
    "Leona"                : 72,
    "Lillia"               : 73,
    "Lissandra"            : 74,
    "Lucian"               : 75,
    "Lulu"                 : 76,
    "Lux"                  : 77,
    "Malphite"             : 78,
    "Malzahar"             : 79,
    "Maokai"               : 80,
    "Master Yi"            : 81,
    "Mel"                  : 82,
    "Milio"                : 83,
    "Miss Fortune"         : 84,
    "Mordekaiser"          : 85,
    "Morgana"              : 86,
    "Naafiri"              : 87,
    "Nami"                 : 88,
    "Nasus"                : 89,
    "Nautilus"             : 90,
    "Neeko"                : 91,
    "Nidalee"              : 92,
    "Nilah"                : 93,
    "Nocturne"             : 94,
    "Nunu & Willump"       : 95,
    "Olaf"                 : 96,
    "Orianna"              : 97,
    "Ornn"                 : 98,
    "Pantheon"             : 99,
    "Poppy"                : 100,
    "Pyke"                 : 101,
    "Qiyana"               : 102,
    "Quinn"                : 103,
    "Rakan"                : 104,
    "Rammus"               : 105,
    "Rek'Sai"              : 106,
    "Rell"                 : 107,
    "Renata Glasc"         : 108,
    "Renekton"             : 109,
    "Rengar"               : 110,
    "Riven"                : 111,
    "Rumble"               : 112,
    "Ryze"                 : 113,
    "Samira"               : 114,
    "Sejuani"              : 115,
    "Senna"                : 116,
    "Seraphine"            : 117,
    "Sett"                 : 118,
    "Shaco"                : 119,
    "Shen"                 : 120,
    "Shyvana"              : 121,
    "Singed"               : 122,
    "Sion"                 : 123,
    "Sivir"                : 124,
    "Skarner"              : 125,
    "Smolder"              : 126,
    "Sona"                 : 127,
    "Soraka"               : 128,
    "Swain"                : 129,
    "Sylas"                : 130,
    "Syndra"               : 131,
    "Tahm Kench"           : 132,
    "Taliyah"              : 133,
    "Talon"                : 134,
    "Taric"                : 135,
    "Teemo"                : 136,
    "Thresh"               : 137,
    "Tristana"             : 138,
    "Trundle"              : 139,
    "Tryndamere"           : 140,
    "Twisted Fate"         : 141,
    "Twitch"               : 142,
    "Udyr"                 : 143,
    "Urgot"                : 144,
    "Varus"                : 145,
    "Vayne"                : 146,
    "Veigar"               : 147,
    "Vel'Koz"              : 148,
    "Vex"                  : 149,
    "Vi"                   : 150,
    "Viego"                : 151,
    "Viktor"               : 152,
    "Vladimir"             : 153,
    "Volibear"             : 154,
    "Warwick"              : 155,
    "Wukong"               : 156,
    "Xayah"                : 157,
    "Xerath"               : 158,
    "Xin Zhao"             : 159,
    "Yasuo"                : 160,
    "Yone"                 : 161,
    "Yorick"               : 162,
    "Yunara"               : 163,
    "Yuumi"                : 164,
    "Zaahen"               : 165,
    "Zac"                  : 166,
    "Zed"                  : 167,
    "Zeri"                 : 168,
    "Ziggs"                : 169,
    "Zilean"               : 170,
    "Zoe"                  : 171,
    "Zyra"                 : 172,
}